[package]
name = "ledger"
version = "0.1.0"
edition = "2021"

[dependencies]
const-hex = "1.10.0"
derive_more = "0.99.17"
ethabi = "18.0.0"
ethereum-types = "0.14.1"
ethers-core = "2.0.11"
eyre = "0.6.9"
hex-literal = "0.4.1"
jsonrpsee = { version = "0.20.3", features = ["server"] }
revm = "3.5.0"
rlp = "0.5.2"
serde = "1.0.193"
serde-enum-str = "0.4.0"
serde_json = "1.0.108"
thiserror = "1.0.50"
tiny-keccak = "2.0.2"
tokio = { version = "1.34.0", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }

[dev-dependencies]
binary_macros = "1.0.0"
serial_test = "2.0.0"
stringreader = "0.1.1"
