[package]
name = "ledger"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
const-hex = "1.10.0"
derive_more = "0.99.17"
derive-new = "0.6.0"
ethabi = "18.0.0"
ethereum-types = "0.14.1"
ethers-core = "2.0.11"
eyre = "0.6.9"
hex-literal = "0.4.1"
itertools = "0.12.0"
jsonrpsee = { version = "0.21.0", features = ["server"] }
keccak-hasher = "0.15.0" # this version must be compatible with triehash
metrics = "0.21.1"
metrics-exporter-prometheus = "0.12.2"
paste = "1.0.14"
phf = "0.11.2"
pin-project = "1.1.3"
quote = "1.0.33"
revm = "3.5.0"
rlp = "0.5.2"
serde = "1.0.193"
serde_json = "1.0.108"
strum = "0.25.0"
thiserror = "1.0.50"
tokio = { version = "1.34.0", features = ["rt-multi-thread", "macros"] }
tower = "0.4.13"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }
triehash = "0.8.4"

[dev-dependencies]
binary_macros = "1.0.0"
serial_test = "2.0.0"
stringreader = "0.1.1"

[build-dependencies]
const-hex = "1.10.0"
nom = "7.1.3"
phf_codegen = "0.11.2"

[lints.clippy]
clone_on_ref_ptr = "warn"
disallowed_names = "warn"
manual_let_else = "warn"
semicolon_if_nothing_returned = "warn"
